### ISSUE TITLE
Encrypted tree implementation?

### ISSUE THREAD

**Issue by Pibborn** [intuit/Decision-Trees-over-FHE#1]
Hi,

Thank you for releasing the code! 

I was wondering if the current version of the code also includes the procedure for “tree encryption” outlined in Section 4.1.1 of your paper (https://dl.acm.org/doi/pdf/10.1145/3517197). Do you have also some recommendations w.r.t. reproducing the experimental results contained in your paper?

Thank you kindly!

**Comment by Pibborn** [comment]
Hi,

could I kindly ask again for feedback on the question above? Thanks!

**Comment by margar8** [comment]
Hi Pibborn,

The code implements prediction on cleartext tree, and we have not implemented the encrypted tree prediction version.
You should be able to reproduce the running time reported in the journal version of TOPS  using this repo and measuring the time of server tree evaluation.

thanks,
Margarita Vald

**Comment by Pibborn** [comment]
Thank you!
